# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’
use_frameworks!
target 'nutri-facts' do
pod 'AFNetworking', '~> 2.5'
pod 'ASValueTrackingSlider'
pod 'RealmSwift'
pod 'AMTagListView'
pod 'UIFloatLabelTextField'
pod 'FCUUID'
end

